systemProp.javax.net.ssl.trustStore=NUL
systemProp.javax.net.ssl.trustStoreType=WINDOWS-ROOT
systemProp.javax.net.ssl.checkServerIdentity=false
systemProp.com.sun.net.ssl.checkRevocation=false
systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3

org.gradle.jvmargs=-Xmx3G -Djavax.net.ssl.trustStore=NUL -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true

mod_id=simplep2p
mod_name=\u7B80\u6613\u8054\u673A
mod_version=1.0.0
mod_authors=\u7B80\u6613\u8054\u673A Team
mod_description=\u7B80\u6613\u8054\u673AMod\u3002\u901A\u8FC7\u623F\u95F4\u7801\u8FDB\u884CP2P\u76F4\u8FDE\uFF0C\u6253\u6D1E\u5931\u8D25\u81EA\u52A8\u4E2D\u7EE7\uFF1B\u652F\u6301EasyTier(\u514DToken)\u4E0EOpenP2P(\u5E26Token)\u53CC\u6A21\u5F0F\uFF0C\u65E0\u9700\u516C\u7F51IP\u548C\u7AEF\u53E3\u6620\u5C04\u5373\u53EF\u4E0E\u597D\u53CB\u8054\u673A\u3002

minecraft_version=1.20.1
forge_version=47.4.22
loader_version_range=[47,)
minecraft_version_range=[1.20.1,1.21)
